version: "3"

services:
  mock-server:
    image: mockoon/cli:latest
    command: ["--data", "data", "--port", "3000"]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/your-healthcheck-route || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 2
      start_period: 10s
    ports:
      - 3000:3000
    volumes:
      - ./mocks/mockoon/routes.json:/data:Z
    networks:
      - demo

networks:
  demo:
    driver: bridge
