# Use CentOS Stream 10 as the base image
FROM quay.io/fedora/fedora:42@sha256:37da1dd205816306c42692afcff9e5d46c82652e9be27a4acafef35da876f61b

# Install Python, pip, and development tools
RUN dnf install -y \
    python3-pip \
    'pkgconfig(cairo)' \
    'pkgconfig(cairo-gobject)' \
    'pkgconfig(gobject-introspection-1.0)' \
    'pkgconfig(mariadb)' \
    /usr/bin/pg_config && \
    dnf clean all

# Upgrade pip
RUN python -m pip install --upgrade pip

# Set up a working directory
WORKDIR /workspace
