# Use CentOS Stream 10 as the base image
FROM quay.io/fedora/fedora:42@sha256:c7af46d3945c14ca4ed5c8303b9969d39409494e0ed120e145e7ae2d05ea3e5e

# Install Python, pip, and development tools
RUN dnf install -y \
    python3-pip \
    'pkgconfig(cairo)' \
    'pkgconfig(cairo-gobject)' \
    'pkgconfig(gobject-introspection-1.0)' \
    'pkgconfig(mariadb)' \
    /usr/bin/pg_config && \
    dnf clean all

# Upgrade pip
RUN python -m pip install --upgrade pip

# Set up a working directory
WORKDIR /workspace
