# Use CentOS Stream 10 as the base image
FROM quay.io/fedora/fedora:42@sha256:dbb675ac74dfbea5a3badd96bf5888adf55119cd57f64b29bec4714fd13b0024

# Install Python, pip, and development tools
RUN dnf install -y \
    python3-pip \
    'pkgconfig(cairo)' \
    'pkgconfig(cairo-gobject)' \
    'pkgconfig(gobject-introspection-1.0)' \
    'pkgconfig(mariadb)' \
    /usr/bin/pg_config && \
    dnf clean all

# Upgrade pip
RUN python -m pip install --upgrade pip

# Set up a working directory
WORKDIR /workspace
